### ISSUE TITLE
Client neocmake quit with exit code 101 and signal 0.

### ISSUE THREAD

**Issue by ccwanggl** [neocmakelsp/neocmakelsp#116]
I use studio config as readme tip

Log as below:
[START][2024-10-10 11:45:08] LSP logging initiated
[ERROR][2024-10-10 11:45:08] .../vim/lsp/rpc.lua:770	"rpc"	"C:\\Users\\cnm2020\\AppData\\Local\\nvim-data\\mason\\bin\\neocmakelsp.CMD"	"stderr"	"\27[2m2024-10-10T03:45:08.287219Z\27[0m \27[32m INFO\27[0m \27[2mneocmakelsp::languageserver\27[0m\27[2m:\27[0m find cache-v2 json, start reading the data\n\27[2m2024-10-10T03:45:08.287381Z\27[0m \27[32m INFO\27[0m \27[2mneocmakelsp::languageserver\27[0m\27[2m:\27[0m Finish getting the data in cache-v2 json\n"
[ERROR][2024-10-10 11:45:08] .../vim/lsp/rpc.lua:770	"rpc"	"C:\\Users\\cnm2020\\AppData\\Local\\nvim-data\\mason\\bin\\neocmakelsp.CMD"	"stderr"	"thread 'main' panicked at C:\\Users\\cnm2020\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\neocmakelsp-0.8.6\\src\\complete.rs:234:46:\nbyte index 29 is out of bounds of `# find_package(fmt REQUIRED)`\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"

**Comment by ccwanggl** [comment]
My environment is Windows 10
powershell

**Comment by Decodetalkers** [comment]
I see, there are two lines before this function? Emm.. I will fix it tonight

**Comment by Decodetalkers** [comment]
Can you try if that pr solve your problem?
