### ISSUE TITLE
aarch64 binary?

### ISSUE THREAD

**Issue by sadguitarius** [neocmakelsp/neocmakelsp#122]
Hi, any chance of providing an aarch64 binary for Linux in the build actions? Cargo's taking quite a while to build on Raspberry Pi. Thank you!

**Comment by Decodetalkers** [comment]
Thanks for your report. I do not very familiar with the action of arch, I will be glad that if you can make a pr for me

**Comment by sadguitarius** [comment]
Ah ok. I actually have no idea either, but I'll give it a shot. Thank you!

**Comment by eeeXun** [comment]
https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/

> Arm runners are available to customers on our Team and Enterprise Cloud plans. We expect to begin offering Arm runners for open source and personal accounts by the end of the year.

**Comment by eeeXun** [comment]
Maybe we can try cross compile? I saw [texlab](https://github.com/latex-lsp/texlab/blob/master/.github/workflows/publish.yml) compiles from aarch64 to x86-64.

**Comment by sadguitarius** [comment]
Thanks, that's helpful to know! I was just checking out the docs for distributed compilation with sccache, which seems like a good option. I'll give it a shot.

**Comment by Decodetalkers** [comment]
https://github.com/neocmakelsp/neocmakelsp/actions/runs/11571163835?pr=128 @eeeXun , can you try the target here? To check if it will works on your platform

**Comment by Decodetalkers** [comment]
solved by https://github.com/neocmakelsp/neocmakelsp/pull/128, you take a try for the built target

**Comment by eeeXun** [comment]
> https://github.com/neocmakelsp/neocmakelsp/actions/runs/11571163835?pr=128 @eeeXun , can you try the target here? To check if it will works on your platform

Sorry, I don't have any arm64 computer for testing. @sadguitarius, can you try it?

**Comment by sadguitarius** [comment]
Just tried and it works perfectly! Thanks so much

**Comment by Decodetalkers** [comment]
ok, done
