### ISSUE TITLE
0.8.11 crash

### ISSUE THREAD

**Issue by ILoveGoulash** [neocmakelsp/neocmakelsp#125]
Hello, using 0.8.11 (installed via cargo on MacOS) in `--stdio` mode via Emacs 29, I'm getting the following crash:
```
[stderr] thread 'main' panicked at /Users/anon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/neocmakelsp-0.8.11/src/utils/findpackage/packagemac.rs:50:18:
[stderr] called `Option::unwrap()` on a `None` value
[stderr] stack backtrace:
[stderr]    0: _rust_begin_unwind
[stderr]    1: core::panicking::panic_fmt
[stderr]    2: core::panicking::panic
[stderr]    3: core::option::unwrap_failed
[stderr]    4: neocmakelsp::utils::findpackage::packagemac::get_cmake_message_with_prefixes
[stderr]    5: neocmakelsp::utils::findpackage::get_cmake_message
[stderr]    6: std::sync::once::Once::call_once::{{closure}}
[stderr]    7: std::sys::sync::once::queue::Once::call
[stderr]    8: neocmakelsp::utils::findpackage::get_cmake_packages_withkeys
[stderr]    9: std::sync::once::Once::call_once::{{closure}}
[stderr]   10: std::sys::sync::once::queue::Once::call
[stderr]   11: neocmakelsp::complete::get_cmake_package_complete
[stderr]   12: neocmakelsp::complete::getsubcomplete
[stderr]   13: neocmakelsp::complete::update_cache::{{closure}}
[stderr]   14: neocmakelsp::languageserver::<impl tower_lsp::LanguageServer for neocmakelsp::Backend>::did_open::{{closure}}
[stderr]   15: tower_lsp::jsonrpc::router::Router<S,E>::method::{{closure}}::{{closure}}::{{closure}}
[stderr]   16: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
[stderr]   17: <tower_lsp::service::LspService<S> as tower_service::Service<tower_lsp::jsonrpc::request::Request>>::call::{{closure}}
[stderr]   18: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
[stderr]   19: neocmakelsp::main::{{closure}}.11192
[stderr]   20: neocmakelsp::main
[stderr] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

<details>
<summary>Full eglot event log</summary>
<pre>
[internal] Mon Oct 21 12:15:23 2024:
(:message "Running language server: neocmakelsp --stdio")
[client-request] (id:1) Mon Oct 21 12:15:23 2024:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 19452 :rootPath "/Users/anon/Dev/SimAndSize/" :rootUri "file:///Users/anon/Dev/SimAndSize" :initializationOptions #s(hash-table size 1 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                                                                              ())
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges t)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t :workspaceFolders t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false :deprecatedSupport t :tagSupport
                                                               (:valueSet
                                                                [1]))
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)
                                               :activeParameterSupport t))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :declaration
                        (:dynamicRegistration :json-false :linkSupport t)
                        :implementation
                        (:dynamicRegistration :json-false :linkSupport t)
                        :typeDefinition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :documentSymbol
                        (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
                                              :isPreferredSupport t)
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false :codeDescriptionSupport :json-false :tagSupport
                                             (:valueSet
                                              [1 2])))
                       :experimental #s(hash-table size 1 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                   ()))
                      :workspaceFolders
                      [(:uri "file:///Users/anon/Dev/SimAndSize" :name "~/Dev/SimAndSize/")]))
[server-reply] (id:1) Mon Oct 21 12:15:23 2024:
(:jsonrpc "2.0" :result
          (:capabilities
           (:completionProvider
            (:resolveProvider :json-false)
            :definitionProvider t :documentFormattingProvider t :documentLinkProvider
            (:resolveProvider t :workDoneProgress :json-false)
            :documentSymbolProvider t :hoverProvider t :referencesProvider t :textDocumentSync
            (:change 1 :openClose t :save t :willSave :json-false :willSaveWaitUntil :json-false)
            :workspace
            (:workspaceFolders
             (:changeNotifications t :supported t)))
           :serverInfo
           (:name "neocmakelsp" :version "0.8.11"))
          :id 1)
[client-notification] Mon Oct 21 12:15:23 2024:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 1 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                            ()))
[client-notification] Mon Oct 21 12:15:23 2024:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
          (:textDocument
           (:uri "file:///Users/anon/Dev/SimAndSize/CMakeLists.txt" :version 0 :languageId "cmake" :text "cmake_minimum_required(VERSION 3.19 FATAL_ERROR)\nproject(SimAndSize VERSION 2.0.1 LANGUAGES CXX)\n\n#...")))
[client-notification] Mon Oct 21 12:15:23 2024:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
          (:settings #s(hash-table size 1 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                   ())))
[server-request] (id:0) Mon Oct 21 12:15:24 2024:
(:jsonrpc "2.0" :method "client/registerCapability" :params
          (:registrations
           [(:id "CMakeCacheWatcher" :method "workspace/didChangeWatchedFiles" :registerOptions
                 (:watchers
                  [(:globPattern "**/CMakeCache.txt" :kind 7)
                   (:globPattern "**/.cmake/api/v1/reply/*.json" :kind 7)
                   (:globPattern "**/CMakeLists.txt" :kind 5)]))])
          :id 0)
[client-reply] (id:0) Mon Oct 21 12:15:24 2024:
(:jsonrpc "2.0" :id 0 :result nil)
[stderr] thread 'main' panicked at /Users/anon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/neocmakelsp-0.8.11/src/utils/findpackage/packagemac.rs:50:18:
[stderr] called `Option::unwrap()` on a `None` value
[stderr] stack backtrace:
[stderr]    0: _rust_begin_unwind
[stderr]    1: core::panicking::panic_fmt
[stderr]    2: core::panicking::panic
[stderr]    3: core::option::unwrap_failed
[stderr]    4: neocmakelsp::utils::findpackage::packagemac::get_cmake_message_with_prefixes
[stderr]    5: neocmakelsp::utils::findpackage::get_cmake_message
[stderr]    6: std::sync::once::Once::call_once::{{closure}}
[stderr]    7: std::sys::sync::once::queue::Once::call
[stderr]    8: neocmakelsp::utils::findpackage::get_cmake_packages_withkeys
[stderr]    9: std::sync::once::Once::call_once::{{closure}}
[stderr]   10: std::sys::sync::once::queue::Once::call
[stderr]   11: neocmakelsp::complete::get_cmake_package_complete
[stderr]   12: neocmakelsp::complete::getsubcomplete
[stderr]   13: neocmakelsp::complete::update_cache::{{closure}}
[stderr]   14: neocmakelsp::languageserver::<impl tower_lsp::LanguageServer for neocmakelsp::Backend>::did_open::{{closure}}
[stderr]   15: tower_lsp::jsonrpc::router::Router<S,E>::method::{{closure}}::{{closure}}::{{closure}}
[stderr]   16: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
[stderr]   17: <tower_lsp::service::LspService<S> as tower_service::Service<tower_lsp::jsonrpc::request::Request>>::call::{{closure}}
[stderr]   18: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
[stderr]   19: neocmakelsp::main::{{closure}}.11192
[stderr]   20: neocmakelsp::main
[stderr] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[internal] Mon Oct 21 12:15:26 2024:
(:message "Connection state changed" :change "exited abnormally with code 101\n")

----------b---y---e---b---y---e----------
[stderr] 
[stderr] 
[stderr] nil
[stderr] nil
[stderr] Process EGLOT (SimAndSize/(cmake-mode)) stderr finished
</pre>
</detail>

**Comment by Decodetalkers** [comment]
Fixed, thanks! it is an serious bug, so I think I should publish a new release for it

**Comment by ILoveGoulash** [comment]
Wow, you work fast! Thanks!
