### ISSUE TITLE
crash such as follow: byte index 53 is out of bounds of

### ISSUE THREAD

**Issue by valord577** [neocmakelsp/neocmakelsp#136]
![屏幕截图 2024-12-20 002746](https://github.com/user-attachments/assets/83fd44d5-d93e-4cd0-935a-f1e69ff24015)

**Comment by Decodetalkers** [comment]
I see . I just haven't thought that add_subdirectly  can have a second line..

**Comment by Decodetalkers** [comment]
fixed in master. Can you take a try?

**Comment by valord577** [comment]
Use the following command line for installation?

```shell
cargo install --git https://github.com/neocmakelsp/neocmakelsp.git --rev [23ec2e0](https://github.com/neocmakelsp/neocmakelsp/commit/23ec2e07fcabdffe2c908ec5c04fad4209eadbbc)
```

**Comment by valord577** [comment]
@Decodetalkers  All Rright!

<img width="1090" alt="image" src="https://github.com/user-attachments/assets/10d110db-b4ad-4f01-a7fb-c10a90f97fac" />

**Comment by Decodetalkers** [comment]
ok, I will publish a new version

**Comment by Decodetalkers** [comment]
closed
