### ISSUE TITLE
[feature] document link

### ISSUE THREAD

**Issue by Freed-Wu** [neocmakelsp/neocmakelsp#39]
Provide links for:

- `file:///the/path/CMakeLists.txt` for `add_subdirectory(the/path)`
- `file:///the/path.cmake` for `include(/the/path.cmake)`

TIA!

**Comment by Decodetalkers** [comment]
Emm.. what is the document link for? I do not know it very much

**Comment by Freed-Wu** [comment]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentLink

**Comment by Decodetalkers** [comment]
Ok, done, I will publish it next week
