### ISSUE TITLE
0.8.0: error[E0658]: use of unstable library feature 'lazy_cell'

### ISSUE THREAD

**Issue by yurivict** [neocmakelsp/neocmakelsp#93]
Both rust-1.79.0 and rust-nightly-1.80.0.20240507 fail to compile it:

```
error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/complete.rs:21:5
   |
21 | use std::sync::LazyLock;
   |     ^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/complete.rs:27:28
   |
27 | pub static COMPLETE_CACHE: LazyLock<Arc<Mutex<CompleteKV>>> =
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
```

FreeBSD 14.1

**Comment by Decodetalkers** [comment]
emm.. I think maybe should wait for new rust for freebsd will be better.. This feature is stable in rust 1.80, and 1.80 is the latest stable version of rust

**Comment by CS-liujf** [comment]
> emm.. I think maybe should wait for new rust for freebsd will be better.. This feature is stable in rust 1.80, and 1.80 is the latest stable version of rust. You can wait until the new version of rust is packaged to freebsd, then compile neocmakelsp.. When I finded that 1.80 is in archlinux, Then I replaced all once_cell to that in std in neocmakelsp. If you are using rustup, just run rustup update , update to the latest rust will fix it

I installed rust-1.79.0 by nix, where the latest version is just 1.79. I encoutered the same problem. How should I do rather than watiting for the 1.80? Install an older newcmakelsp?

**Comment by Decodetalkers** [comment]
> > emm.. I think maybe should wait for new rust for freebsd will be better.. This feature is stable in rust 1.80, and 1.80 is the latest stable version of rust. You can wait until the new version of rust is packaged to freebsd, then compile neocmakelsp.. When I finded that 1.80 is in archlinux, Then I replaced all once_cell to that in std in neocmakelsp. If you are using rustup, just run rustup update , update to the latest rust will fix it
> 
> I installed rust-1.79.0 by nix, where the latest version is just 1.79. I encoutered the same problem. How should I do rather than watiting for the 1.80? Install a previous version of newcmakelsp?

Sorry for that.. Before I thought two weeks will be enough for Distro to package new version of rust.. sorry again.. maybe you can try to use the assert from the github

**Comment by Decodetalkers** [comment]
> > emm.. I think maybe should wait for new rust for freebsd will be better.. This feature is stable in rust 1.80, and 1.80 is the latest stable version of rust. You can wait until the new version of rust is packaged to freebsd, then compile neocmakelsp.. When I finded that 1.80 is in archlinux, Then I replaced all once_cell to that in std in neocmakelsp. If you are using rustup, just run rustup update , update to the latest rust will fix it
> 
> I installed rust-1.79.0 by nix, where the latest version is just 1.79. I encoutered the same problem. How should I do rather than watiting for the 1.80? Install a previous version of newcmakelsp?

https://github.com/NixOS/nixpkgs/pull/332153 rust 1.80 has been supported by nixos, have your problem been solved now? Emm

**Comment by CS-liujf** [comment]
> > > emm.. I think maybe should wait for new rust for freebsd will be better.. This feature is stable in rust 1.80, and 1.80 is the latest stable version of rust. You can wait until the new version of rust is packaged to freebsd, then compile neocmakelsp.. When I finded that 1.80 is in archlinux, Then I replaced all once_cell to that in std in neocmakelsp. If you are using rustup, just run rustup update , update to the latest rust will fix it
> > 
> > 
> > I installed rust-1.79.0 by nix, where the latest version is just 1.79. I encoutered the same problem. How should I do rather than watiting for the 1.80? Install a previous version of newcmakelsp?
> 
> [NixOS/nixpkgs#332153](https://github.com/NixOS/nixpkgs/pull/332153) rust 1.80 has been supported by nixos, have your problem been solved now? Emm

Acutally, the [nixpkgs](https://search.nixos.org/packages?channel=unstable&show=rustc&from=0&size=50&sort=relevance&type=packages&query=rustc) with unstable channel only provide rust-1.79 up to now. So I use rustup to install rust 1.80 instead. Thanks.

**Comment by doulighan** [comment]
`rustup update` fixed it for me

**Comment by Decodetalkers** [comment]
I will close this issue now.. thanks for report
